
name: Reusable check workflow
on:
  workflow_call:

# shared check jobs
jobs:
  check_source:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # setup global dependencies
    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./ui-package/package-lock.json
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ./ui-package/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./ui-package/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Prepare test environment
      run: mkdir -p ui-package/dist && touch ui-package/dist/dummy

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Check go fmt
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Run staticcheck
      run: staticcheck ./...

    #- name: Install golint
    #  run: go install golang.org/x/lint/golint@latest
    #- name: Run golint
    #  run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    
    # build UI package
    - name: Build UI package
      run: |
        make build-ui
    